language: r
sudo: false
cache: packages

r:
 - oldrel
 - release
 - devel

branches:
  except:
    - example-data
    - gh-pages

apt_packages: 
    - gdal-bin
    - libgdal-dev
    - libxml2-dev
    - libproj-dev

notifications:
  email:
    on_success: change
    on_failure: change

